require_relative "../lib/top_vacation_spots/version"
require 'nokogiri'
require 'open-uri'
require 'httparty'
require "pry"
require_relative "../lib/cli"
require_relative "../lib/scraper"
require_relative "../lib/vacation"
require_relative "../lib/region"